language: ruby
before_install: gem install bundler -v 1.11.2
script: "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-2
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
notifications:
  email:
    - pnascimento@gmail.com
    - oriekenjr@gmail.com
